version: "3.8"
services:
  react:
    build: ./
    container_name: node
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true